### ISSUE TITLE
Youtube Not playing songs

### ISSUE THREAD

**Issue by CJFitchett2009** [Wizkiller96/WizBot#28]
0 12:52:48 MusicService | Done creating
0 12:52:48 YtdlOperation | Executing youtube-dl -4 --geo-bypass -f bestaudio -e --get-url --get-id --get-thumbnail --get-duration --no-check-certificate --default-search "ytsearch:" "Faded"
0 12:52:48 YoutubeResolveStrategy | No song found. Data less than 6
0 12:52:48 YoutubeResolveStrategy | Searching for video
0 12:52:51 YoutubeResolveStrategy | YoutubeExplode.Exceptions.TransientFailureException: Playlist response is broken.
In most cases, this error indicates that the problem is on YouTube's side and this is not a bug in the library.
To resolve this error, please wait some time and try again.
If this issue persists, please report it on the project's GitHub page.
   at YoutubeExplode.ReverseEngineering.Responses.PlaylistResponse.Parse(String raw)
   at YoutubeExplode.ReverseEngineering.Responses.PlaylistResponse.<>c__DisplayClass13_0.<<GetSearchResultsAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at YoutubeExplode.Internal.Retry.WrapAsync[T](Func`1 executeAsync)
   at YoutubeExplode.Internal.Retry.WrapAsync[T](Func`1 executeAsync)
   at YoutubeExplode.ReverseEngineering.Responses.PlaylistResponse.GetSearchResultsAsync(YoutubeHttpClient httpClient, String query, Int32 page)
   at YoutubeExplode.Search.SearchClient.GetVideosAsync(String searchQuery, Int32 startPage, Int32 pageCount)
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetResult(Int16 token)
   at YoutubeExplode.Search.SearchClient.GetVideosAsync(String searchQuery, Int32 startPage, Int32 pageCount)
   at YoutubeExplode.Internal.Extensions.AsyncEnumerableExtensions.ToListAsync[T](IAsyncEnumerable`1 asyncEnumerable)
   at YoutubeExplode.Internal.Extensions.AsyncEnumerableExtensions.ToListAsync[T](IAsyncEnumerable`1 asyncEnumerable)
   at YoutubeExplode.AccessibilityExtensions.BufferAsync(IAsyncEnumerable`1 asyncVideoEnumerable)
   at WizBot.Modules.Music.Common.SongResolver.Strategies.YoutubeResolveStrategy.ResolveWithYtExplode(String query) in C:\Users\CJ\Desktop\bot\WizBot\WizBot.Core\Modules\Music\Common\SongResolver\Strategies\YoutubeResolveStrategy.cs:line 44
   at WizBot.Modules.Music.Common.SongResolver.Strategies.YoutubeResolveStrategy.ResolveSong(String query) in C:\Users\CJ\Desktop\bot\WizBot\WizBot.Core\Modules\Music\Common\SongResolver\Strategies\YoutubeResolveStrategy.cs:line 33

**Comment by Wizkiller96** [comment]
Make sure you have all prerequisites installed correctly http://docs.wizbot.cc/en/latest/guides/from-source/#prerequisites But it seems to be an issue with the youtube side as the error is stating.

**Comment by CJFitchett2009** [comment]
I have all of them installed.
